#!/usr/bin/env php
<?php

declare(strict_types=1);

use App\Kernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;

require_once __DIR__ . '/vendor/autoload.php';

$kernel = new Kernel($_SERVER['APP_ENV'] ?? 'test', (bool)($_SERVER['APP_DEBUG'] ?? false));
$kernel->boot();

$application = new Application($kernel);
$application->run();
