name: Tests

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Validate composer.json
        run: composer validate --strict

      - name: Composer Audit
        run: composer audit

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run code style checks
        run: composer lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        include:
          - php-version: '8.1'
            symfony-version: '6.4.*'

          - php-version: '8.2'
            symfony-version: '6.4.*'
          - php-version: '8.2'
            symfony-version: '7.0.*'

          - php-version: '8.3'
            symfony-version: '6.4.*'
          - php-version: '8.3'
            symfony-version: '7.0.*'
          - php-version: '8.3'
            symfony-version: '7.1.*'
          - php-version: '8.3'
            symfony-version: '7.2.*'

          - php-version: '8.4'
            symfony-version: '6.4.*'
          - php-version: '8.4'
            symfony-version: '7.0.*'
          - php-version: '8.4'
            symfony-version: '7.1.*'
          - php-version: '8.4'
            symfony-version: '7.2.*'
          - php-version: '8.4'
            symfony-version: '7.3.*'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Create var directory
        run: mkdir -p var

      - name: Update Symfony constraints in composer.json
        run: |
          export SYMFONY_VERSION=${{ matrix.symfony-version }}
          sed -i -E "s/(\"symfony\/[a-z-]+\":\s*\")[^\"]+/\1$SYMFONY_VERSION/g" composer.json

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run tests
        run: composer test
