name: Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  run:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        php-versions: ['8.3']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create var dir
        run: mkdir var

      - name: Composer validate
        run: composer validate --strict

      - name: Composer install
        run: composer install

      - name: Codestyle
        run: composer lint

      - name: Tests
        run: composer test
