name: Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  run:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php-version: '8.1'
            symfony-version: '6.4.*'

#          - php-version: '8.2'
#            symfony-version: '6.4.*'
#          - php-version: '8.2'
#            symfony-version: '7.0.*'
#
#          - php-version: '8.3'
#            symfony-version: '6.4.*'
#          - php-version: '8.3'
#            symfony-version: '7.0.*'
#          - php-version: '8.3'
#            symfony-version: '7.1.*'
#          - php-version: '8.3'
#            symfony-version: '7.2.*'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Create var directory
        run: mkdir -p var

      - name: Update Symfony constraints in composer.json
        run: |
          export SYMFONY_VERSION=${{ matrix.symfony-version }}
          sed -i -E "s/(\"symfony\/[a-z-]+\":\s*\")[^\"]+/\1$SYMFONY_VERSION/g" composer.json

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run code style checks
        run: composer lint || echo "No lint script defined"

      - name: Run tests
        run: composer test || echo "No test script defined"
